name: Upload Terraform Config to S3
 
on:
  workflow_dispatch:
    inputs:
      folder:
        description: 'Choose Terraform product (EC2,VPC..etc)'
        required: true
        type: choice
        options:
          - EC2
          - VPC
permissions:
   contents: write
   id-token: write
jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: 'us-west-2' 
      AWS_S3_BUCKET: 'nsh-state-new'  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Create tar.gz archive
        run: |
          cd ${{ github.event.inputs.folder }}
          tar -czvf ../${{ github.event.inputs.folder }}.tar.gz .
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::183114607892:role/github_actions_oidc
          role-session-name: githubactions
          aws-region: us-west-2

      - name: Upload to S3
        run: |
          aws s3 cp ${{ github.event.inputs.folder }}.tar.gz s3://$AWS_S3_BUCKET/
